server:
  port: 9002

spring:
  datasource:
    #引入druid数据源
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.13.167.45:3306/taotao?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: xiexinismine

dubbo:
  scan:
    basePackages: cn.tt
  application:
    name: provider-web
  registry:
    address: zookeeper://106.13.58.226:2181?backup=106.12.201.215:2182,106.12.82 .143:2183
  protocol:
    name: dubbo
    port: 20881


mybatis-plus:
  type-aliases-package: cn.tt.pojo       #配置别名包路径
  mapper-locations: classpath:/mybatis/mappers/*.xml  #添加mapper映射文件
  configuration:
    map-underscore-to-camel-case: true                #开启驼峰映射规则